sonar.projectKey=online-blood-donation-system-ui
sonar.projectName=Online Blood Donation System - UI
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,src/serviceWorker.js,src/assets/**
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.sourceEncoding=UTF-8
